### ISSUE TITLE
Features Request

### ISSUE THREAD

**Issue by krackxor** [sahilgit55/VideoFlux-Re#3]
Hai bro

Could you kindly consider adding a new fixture?

In the "/settings" section, could we please include an option to modify the audio type?

Additionally, in the "/sofmux" section, could we add an audio option?

It would be greatly appreciated if we could also incorporate the "trims" command to trim videos.

Furthermore, could we include an "extract" command to extract audio and subtitles?

**Comment by Aluval** [comment]
Hello bro one time in telegram dm me @sunrises_24

**Comment by krackxor** [comment]
No update 🥲

**Comment by Aluval** [comment]
> No update 🥲

Once dm me in telegram bro @krackxor 

@Sunrises_24
